
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador.lenguaje;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int imprimir = 30;
  public static final int correrdasm = 31;
  public static final int corcheteC = 27;
  public static final int corcheteA = 26;
  public static final int coma = 3;
  public static final int igual = 14;
  public static final int identificador = 39;
  public static final int sinosi = 25;
  public static final int caracter = 43;
  public static final int mayorque = 19;
  public static final int nativaOvalo = 34;
  public static final int menorIgual = 16;
  public static final int si = 23;
  public static final int mientras = 28;
  public static final int nativaCadena = 35;
  public static final int nativaCuadrado = 33;
  public static final int smash = 46;
  public static final int menos = 7;
  public static final int EOF = 0;
  public static final int mas = 6;
  public static final int verdadero = 45;
  public static final int mayorIgual = 17;
  public static final int para = 29;
  public static final int error = 1;
  public static final int nativaPunto = 32;
  public static final int entero = 40;
  public static final int or = 20;
  public static final int menorque = 18;
  public static final int integer = 2;
  public static final int potencia = 10;
  public static final int incremento = 12;
  public static final int falso = 44;
  public static final int multi = 8;
  public static final int nativaLinea = 36;
  public static final int diferente = 15;
  public static final int and = 21;
  public static final int decremento = 13;
  public static final int puntocoma = 4;
  public static final int parC = 38;
  public static final int parA = 37;
  public static final int div = 9;
  public static final int asignacion = 5;
  public static final int no = 22;
  public static final int decimal = 41;
  public static final int modulo = 11;
  public static final int cadena = 42;
  public static final int sino = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "integer",
  "coma",
  "puntocoma",
  "asignacion",
  "mas",
  "menos",
  "multi",
  "div",
  "potencia",
  "modulo",
  "incremento",
  "decremento",
  "igual",
  "diferente",
  "menorIgual",
  "mayorIgual",
  "menorque",
  "mayorque",
  "or",
  "and",
  "no",
  "si",
  "sino",
  "sinosi",
  "corcheteA",
  "corcheteC",
  "mientras",
  "para",
  "imprimir",
  "correrdasm",
  "nativaPunto",
  "nativaCuadrado",
  "nativaOvalo",
  "nativaCadena",
  "nativaLinea",
  "parA",
  "parC",
  "identificador",
  "entero",
  "decimal",
  "cadena",
  "caracter",
  "falso",
  "verdadero",
  "smash"
  };
}

